#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Teleconsult.Android.Resource", IsApplication=true)]

namespace Teleconsult.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Macaw.UIComponents.Resource.String.ApplicationName = global::Teleconsult.Android.Resource.String.ApplicationName;
			global::Macaw.UIComponents.Resource.String.Hello = global::Teleconsult.Android.Resource.String.Hello;
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int bottom_in = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int bottom_out = 2130968577;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f090001
			public const int context_menu = 2131296257;
			
			// aapt resource value: 0x7f090000
			public const int country_array = 2131296256;
			
			// aapt resource value: 0x7f090002
			public const int gender_array = 2131296258;
			
			// aapt resource value: 0x7f090004
			public const int sort_priority = 2131296260;
			
			// aapt resource value: 0x7f090005
			public const int status_expert = 2131296261;
			
			// aapt resource value: 0x7f090003
			public const int timezone_array = 2131296259;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int typeface = 2130771968;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f060008
			public const int background_slider = 2131099656;
			
			// aapt resource value: 0x7f06000f
			public const int bg_color = 2131099663;
			
			// aapt resource value: 0x7f060005
			public const int black = 2131099653;
			
			// aapt resource value: 0x7f060000
			public const int blue = 2131099648;
			
			// aapt resource value: 0x7f06000b
			public const int blue_landing = 2131099659;
			
			// aapt resource value: 0x7f060013
			public const int btn_popup_color = 2131099667;
			
			// aapt resource value: 0x7f06000d
			public const int button_past_history = 2131099661;
			
			// aapt resource value: 0x7f06000e
			public const int button_past_history_press = 2131099662;
			
			// aapt resource value: 0x7f060011
			public const int calling_step = 2131099665;
			
			// aapt resource value: 0x7f060014
			public const int custom_color_tv_forgot_pass = 2131099668;
			
			// aapt resource value: 0x7f060012
			public const int divider_line_popup = 2131099666;
			
			// aapt resource value: 0x7f060001
			public const int green = 2131099649;
			
			// aapt resource value: 0x7f06000a
			public const int green_sky_landing = 2131099658;
			
			// aapt resource value: 0x7f060002
			public const int grey = 2131099650;
			
			// aapt resource value: 0x7f06000c
			public const int grey_app = 2131099660;
			
			// aapt resource value: 0x7f060007
			public const int light_grey = 2131099655;
			
			// aapt resource value: 0x7f060010
			public const int line_booking = 2131099664;
			
			// aapt resource value: 0x7f060006
			public const int orange = 2131099654;
			
			// aapt resource value: 0x7f060003
			public const int red = 2131099651;
			
			// aapt resource value: 0x7f060009
			public const int transparent_grey = 2131099657;
			
			// aapt resource value: 0x7f060004
			public const int white = 2131099652;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f080009
			public const int corner = 2131230729;
			
			// aapt resource value: 0x7f08001c
			public const int height_ed_search_home = 2131230748;
			
			// aapt resource value: 0x7f08000b
			public const int height_header = 2131230731;
			
			// aapt resource value: 0x7f08000c
			public const int height_tab = 2131230732;
			
			// aapt resource value: 0x7f08000a
			public const int min_height_button = 2131230730;
			
			// aapt resource value: 0x7f080005
			public const int pad_bottom = 2131230725;
			
			// aapt resource value: 0x7f080017
			public const int pad_bottom_home = 2131230743;
			
			// aapt resource value: 0x7f08001b
			public const int pad_bottom_home_1 = 2131230747;
			
			// aapt resource value: 0x7f080001
			public const int pad_left = 2131230721;
			
			// aapt resource value: 0x7f080024
			public const int pad_left_header = 2131230756;
			
			// aapt resource value: 0x7f080019
			public const int pad_left_home = 2131230745;
			
			// aapt resource value: 0x7f080002
			public const int pad_right = 2131230722;
			
			// aapt resource value: 0x7f08001a
			public const int pad_right_home = 2131230746;
			
			// aapt resource value: 0x7f080003
			public const int pad_top = 2131230723;
			
			// aapt resource value: 0x7f080004
			public const int pad_top1 = 2131230724;
			
			// aapt resource value: 0x7f08002e
			public const int pad_top_bottom_btn_segmented = 2131230766;
			
			// aapt resource value: 0x7f08002b
			public const int pad_top_bottom_list_search = 2131230763;
			
			// aapt resource value: 0x7f08002d
			public const int pad_top_bottom_popup_sort = 2131230765;
			
			// aapt resource value: 0x7f080028
			public const int pad_top_btn_change_pass = 2131230760;
			
			// aapt resource value: 0x7f080026
			public const int pad_top_btn_signin = 2131230758;
			
			// aapt resource value: 0x7f080025
			public const int pad_top_email_signin = 2131230757;
			
			// aapt resource value: 0x7f080029
			public const int pad_top_first_tv_booking = 2131230761;
			
			// aapt resource value: 0x7f080006
			public const int pad_top_home = 2131230726;
			
			// aapt resource value: 0x7f080007
			public const int pad_top_landing = 2131230727;
			
			// aapt resource value: 0x7f080008
			public const int pad_top_landing1 = 2131230728;
			
			// aapt resource value: 0x7f080027
			public const int pad_top_old_pass_change_pass = 2131230759;
			
			// aapt resource value: 0x7f080023
			public const int pad_top_popup = 2131230755;
			
			// aapt resource value: 0x7f08001e
			public const int pad_top_search_result = 2131230750;
			
			// aapt resource value: 0x7f080000
			public const int pad_top_signin_lading = 2131230720;
			
			// aapt resource value: 0x7f08002a
			public const int pad_top_tv_in_spec_detail = 2131230762;
			
			// aapt resource value: 0x7f08002c
			public const int size_tv_step_calling = 2131230764;
			
			// aapt resource value: 0x7f080011
			public const int text_button_dashboard_size = 2131230737;
			
			// aapt resource value: 0x7f08000f
			public const int text_button_size = 2131230735;
			
			// aapt resource value: 0x7f080012
			public const int text_content_dashboard_size = 2131230738;
			
			// aapt resource value: 0x7f080010
			public const int text_content_size = 2131230736;
			
			// aapt resource value: 0x7f080013
			public const int text_cost_size = 2131230739;
			
			// aapt resource value: 0x7f080014
			public const int text_cost_size1 = 2131230740;
			
			// aapt resource value: 0x7f08000e
			public const int text_pad_left_landing = 2131230734;
			
			// aapt resource value: 0x7f080021
			public const int text_size_notice = 2131230753;
			
			// aapt resource value: 0x7f08001f
			public const int text_size_search_hind_home = 2131230751;
			
			// aapt resource value: 0x7f080020
			public const int text_size_search_result = 2131230752;
			
			// aapt resource value: 0x7f080022
			public const int text_size_title_header = 2131230754;
			
			// aapt resource value: 0x7f08001d
			public const int tv_content_size_pass = 2131230749;
			
			// aapt resource value: 0x7f080018
			public const int wh_avatar = 2131230744;
			
			// aapt resource value: 0x7f08000d
			public const int wh_ic_landing = 2131230733;
			
			// aapt resource value: 0x7f080015
			public const int wh_ic_menu = 2131230741;
			
			// aapt resource value: 0x7f080016
			public const int wh_ic_tab_menu_detail = 2131230742;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int bg_blue_btn = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int bg_dark_blue_btn = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int bg_gray_btn = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int bg_landing_page = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int camera = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int camera_pressed = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int custom_bg_status = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int custom_border_bottom_left_right = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int custom_border_corner_top_left_right = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int custom_border_edittext = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int custom_border_line_top = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int custom_border_listview_item = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int custom_border_menu = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int custom_border_normal = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int custom_border_right = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int custom_border_search_bar = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int custom_border_select = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int custom_btn_white = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int custom_button_no_border = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int custom_button_pasthistory = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int custom_button_segmented_left = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int custom_button_segmented_right = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int custom_icon_left = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int custom_ll_control_segmented = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int custom_padding_logo_actionbar = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int custom_progress_bar = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int custom_splash_center = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int ic_0_star = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int ic_1_star = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int ic_2_star = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int ic_3_star = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int ic_4_star = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int ic_action_overflow = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int ic_app = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int ic_attach = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int ic_available = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int ic_back = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int ic_booktime = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int ic_check = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int ic_check_box = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int ic_check_inactive = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int ic_check_sort = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int ic_close_large = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int ic_close_search = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int ic_delete = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int ic_dollar = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int ic_dollar_cost = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int ic_dropdown = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int ic_emailprofile = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int ic_emailprofile_pressed = 2130837553;
			
			// aapt resource value: 0x7f020032
			public const int ic_enquiry = 2130837554;
			
			// aapt resource value: 0x7f020033
			public const int ic_expired = 2130837555;
			
			// aapt resource value: 0x7f020034
			public const int ic_favorite_selected = 2130837556;
			
			// aapt resource value: 0x7f020035
			public const int ic_favorite_selected_tabbar = 2130837557;
			
			// aapt resource value: 0x7f020036
			public const int ic_favorite_unselect = 2130837558;
			
			// aapt resource value: 0x7f020037
			public const int ic_favorite_unselect_tabbar = 2130837559;
			
			// aapt resource value: 0x7f020038
			public const int ic_filter = 2130837560;
			
			// aapt resource value: 0x7f020039
			public const int ic_home_selected_tabbar = 2130837561;
			
			// aapt resource value: 0x7f02003a
			public const int ic_home_unselect_tabbar = 2130837562;
			
			// aapt resource value: 0x7f02003b
			public const int ic_location = 2130837563;
			
			// aapt resource value: 0x7f02003c
			public const int ic_maybe_available = 2130837564;
			
			// aapt resource value: 0x7f02003d
			public const int ic_not_available = 2130837565;
			
			// aapt resource value: 0x7f02003e
			public const int ic_ontime = 2130837566;
			
			// aapt resource value: 0x7f02003f
			public const int ic_password = 2130837567;
			
			// aapt resource value: 0x7f020040
			public const int ic_profile_selected_tabbar = 2130837568;
			
			// aapt resource value: 0x7f020041
			public const int ic_profile_unselect_tabbar = 2130837569;
			
			// aapt resource value: 0x7f020042
			public const int ic_question = 2130837570;
			
			// aapt resource value: 0x7f020043
			public const int ic_rating_disable = 2130837571;
			
			// aapt resource value: 0x7f020044
			public const int ic_replay = 2130837572;
			
			// aapt resource value: 0x7f020045
			public const int ic_replay_pressed = 2130837573;
			
			// aapt resource value: 0x7f020046
			public const int ic_search_selected_tabbar = 2130837574;
			
			// aapt resource value: 0x7f020047
			public const int ic_search_top = 2130837575;
			
			// aapt resource value: 0x7f020048
			public const int ic_search_unselect_tabbar = 2130837576;
			
			// aapt resource value: 0x7f020049
			public const int ic_selected_actionbar = 2130837577;
			
			// aapt resource value: 0x7f02004a
			public const int ic_star = 2130837578;
			
			// aapt resource value: 0x7f02004b
			public const int ic_star_disable = 2130837579;
			
			// aapt resource value: 0x7f02004c
			public const int ic_status_blue = 2130837580;
			
			// aapt resource value: 0x7f02004d
			public const int ic_status_red = 2130837581;
			
			// aapt resource value: 0x7f02004e
			public const int ic_tab_alert_selected = 2130837582;
			
			// aapt resource value: 0x7f02004f
			public const int ic_tab_alert_unselected = 2130837583;
			
			// aapt resource value: 0x7f020050
			public const int ic_tab_alerts = 2130837584;
			
			// aapt resource value: 0x7f020051
			public const int ic_tab_booking_request_selected = 2130837585;
			
			// aapt resource value: 0x7f020052
			public const int ic_tab_booking_request_unselected = 2130837586;
			
			// aapt resource value: 0x7f020053
			public const int ic_tab_bookingrequests = 2130837587;
			
			// aapt resource value: 0x7f020054
			public const int ic_tab_confirmed_booking_selected = 2130837588;
			
			// aapt resource value: 0x7f020055
			public const int ic_tab_confirmed_booking_unselected = 2130837589;
			
			// aapt resource value: 0x7f020056
			public const int ic_tab_confirmedbookings = 2130837590;
			
			// aapt resource value: 0x7f020057
			public const int ic_tab_custom_text = 2130837591;
			
			// aapt resource value: 0x7f020058
			public const int ic_tab_history_selected = 2130837592;
			
			// aapt resource value: 0x7f020059
			public const int ic_tab_history_unselected = 2130837593;
			
			// aapt resource value: 0x7f02005a
			public const int ic_tab_home = 2130837594;
			
			// aapt resource value: 0x7f02005b
			public const int ic_tab_listfavorite = 2130837595;
			
			// aapt resource value: 0x7f02005c
			public const int ic_tab_my_profile = 2130837596;
			
			// aapt resource value: 0x7f02005d
			public const int ic_tab_pasthistory = 2130837597;
			
			// aapt resource value: 0x7f02005e
			public const int ic_tab_search = 2130837598;
			
			// aapt resource value: 0x7f02005f
			public const int ic_transcribe = 2130837599;
			
			// aapt resource value: 0x7f020060
			public const int ic_transcribe_disable = 2130837600;
			
			// aapt resource value: 0x7f020061
			public const int ic_transcribe_pressed = 2130837601;
			
			// aapt resource value: 0x7f020062
			public const int ic_uncheck_box = 2130837602;
			
			// aapt resource value: 0x7f020063
			public const int ic_unlicensed = 2130837603;
			
			// aapt resource value: 0x7f020064
			public const int ic_unverified = 2130837604;
			
			// aapt resource value: 0x7f020065
			public const int ic_user = 2130837605;
			
			// aapt resource value: 0x7f020066
			public const int ic_verified = 2130837606;
			
			// aapt resource value: 0x7f020067
			public const int ic_waive = 2130837607;
			
			// aapt resource value: 0x7f020068
			public const int ic_waive_disable = 2130837608;
			
			// aapt resource value: 0x7f020069
			public const int ic_waive_pressed = 2130837609;
			
			// aapt resource value: 0x7f02006a
			public const int icon_feedback = 2130837610;
			
			// aapt resource value: 0x7f02006b
			public const int icon_feedback_pressed = 2130837611;
			
			// aapt resource value: 0x7f02006c
			public const int icon_uploadfile = 2130837612;
			
			// aapt resource value: 0x7f02006d
			public const int info_ic = 2130837613;
			
			// aapt resource value: 0x7f02006e
			public const int info_ic_pressed = 2130837614;
			
			// aapt resource value: 0x7f02006f
			public const int logo = 2130837615;
			
			// aapt resource value: 0x7f020070
			public const int logo_popup = 2130837616;
			
			// aapt resource value: 0x7f020071
			public const int magnify = 2130837617;
			
			// aapt resource value: 0x7f020072
			public const int monoandroidsplash = 2130837618;
			
			// aapt resource value: 0x7f020073
			public const int search = 2130837619;
			
			// aapt resource value: 0x7f020074
			public const int selectable_background_actionbar = 2130837620;
			
			// aapt resource value: 0x7f020075
			public const int selector_button = 2130837621;
			
			// aapt resource value: 0x7f020076
			public const int slider_blt_grn = 2130837622;
			
			// aapt resource value: 0x7f020077
			public const int slider_blt_trans = 2130837623;
			
			// aapt resource value: 0x7f020078
			public const int special_home = 2130837624;
			
			// aapt resource value: 0x7f020079
			public const int translucent_background = 2130837625;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0b00a9
			public const int LocalWebView = 2131427497;
			
			// aapt resource value: 0x7f0b00fb
			public const int add = 2131427579;
			
			// aapt resource value: 0x7f0b0000
			public const int arial_bold = 2131427328;
			
			// aapt resource value: 0x7f0b0001
			public const int arial_bold_italic = 2131427329;
			
			// aapt resource value: 0x7f0b0002
			public const int arial_italic = 2131427330;
			
			// aapt resource value: 0x7f0b0003
			public const int arial_normal = 2131427331;
			
			// aapt resource value: 0x7f0b004e
			public const int avatar_past_detail = 2131427406;
			
			// aapt resource value: 0x7f0b0060
			public const int avatar_popup_booking = 2131427424;
			
			// aapt resource value: 0x7f0b0091
			public const int avatar_request_booking = 2131427473;
			
			// aapt resource value: 0x7f0b00b2
			public const int avatar_spec_search = 2131427506;
			
			// aapt resource value: 0x7f0b00f5
			public const int btnAll = 2131427573;
			
			// aapt resource value: 0x7f0b008a
			public const int btnCancelFeeback = 2131427466;
			
			// aapt resource value: 0x7f0b0077
			public const int btnCancelSendEmail = 2131427447;
			
			// aapt resource value: 0x7f0b004b
			public const int btnChangePass = 2131427403;
			
			// aapt resource value: 0x7f0b00f6
			public const int btnComplete = 2131427574;
			
			// aapt resource value: 0x7f0b007f
			public const int btnLibrary = 2131427455;
			
			// aapt resource value: 0x7f0b007b
			public const int btnOkFeedbackReview = 2131427451;
			
			// aapt resource value: 0x7f0b0007
			public const int btnSendActiveCode = 2131427335;
			
			// aapt resource value: 0x7f0b0078
			public const int btnSendEmail = 2131427448;
			
			// aapt resource value: 0x7f0b008b
			public const int btnSendFeedback = 2131427467;
			
			// aapt resource value: 0x7f0b00ac
			public const int btnSendForgotPass = 2131427500;
			
			// aapt resource value: 0x7f0b004c
			public const int btnSignOut = 2131427404;
			
			// aapt resource value: 0x7f0b0080
			public const int btnTakePhoto = 2131427456;
			
			// aapt resource value: 0x7f0b004a
			public const int btnUpdateProfile = 2131427402;
			
			// aapt resource value: 0x7f0b0046
			public const int btn_Search = 2131427398;
			
			// aapt resource value: 0x7f0b006b
			public const int btn_addfile_confirm_booking = 2131427435;
			
			// aapt resource value: 0x7f0b0013
			public const int btn_book_request = 2131427347;
			
			// aapt resource value: 0x7f0b008e
			public const int btn_cancel_entertext_popup = 2131427470;
			
			// aapt resource value: 0x7f0b00a8
			public const int btn_cancel_reschedule = 2131427496;
			
			// aapt resource value: 0x7f0b0025
			public const int btn_change_pass = 2131427365;
			
			// aapt resource value: 0x7f0b00a4
			public const int btn_confirm_booking = 2131427492;
			
			// aapt resource value: 0x7f0b008f
			public const int btn_confirm_entertext_popup = 2131427471;
			
			// aapt resource value: 0x7f0b0070
			public const int btn_confirm_tv_popup = 2131427440;
			
			// aapt resource value: 0x7f0b00a5
			public const int btn_decline_booking = 2131427493;
			
			// aapt resource value: 0x7f0b006c
			public const int btn_decline_confirm_booking = 2131427436;
			
			// aapt resource value: 0x7f0b006f
			public const int btn_decline_tv_popup = 2131427439;
			
			// aapt resource value: 0x7f0b007e
			public const int btn_ok_popup_notice = 2131427454;
			
			// aapt resource value: 0x7f0b00a7
			public const int btn_ok_reschedule = 2131427495;
			
			// aapt resource value: 0x7f0b0048
			public const int btn_registry_home = 2131427400;
			
			// aapt resource value: 0x7f0b006a
			public const int btn_request_talknow_booking = 2131427434;
			
			// aapt resource value: 0x7f0b00a3
			public const int btn_reschedule_booking = 2131427491;
			
			// aapt resource value: 0x7f0b0073
			public const int btn_set_datetime = 2131427443;
			
			// aapt resource value: 0x7f0b00c1
			public const int btn_sigin = 2131427521;
			
			// aapt resource value: 0x7f0b0047
			public const int btn_sigin_home = 2131427399;
			
			// aapt resource value: 0x7f0b00be
			public const int checkbox_remember = 2131427518;
			
			// aapt resource value: 0x7f0b00bf
			public const int checkbox_showpassword = 2131427519;
			
			// aapt resource value: 0x7f0b00fa
			public const int contextMenu = 2131427578;
			
			// aapt resource value: 0x7f0b0071
			public const int datepicker_popup = 2131427441;
			
			// aapt resource value: 0x7f0b0100
			public const int delete = 2131427584;
			
			// aapt resource value: 0x7f0b0004
			public const int ed_code_active = 2131427332;
			
			// aapt resource value: 0x7f0b0045
			public const int edit_Search = 2131427397;
			
			// aapt resource value: 0x7f0b0023
			public const int edit_confirm_newpass = 2131427363;
			
			// aapt resource value: 0x7f0b0074
			public const int edit_enter_email = 2131427444;
			
			// aapt resource value: 0x7f0b0076
			public const int edit_enter_message = 2131427446;
			
			// aapt resource value: 0x7f0b008d
			public const int edit_entertext_popup = 2131427469;
			
			// aapt resource value: 0x7f0b0087
			public const int edit_feedback = 2131427463;
			
			// aapt resource value: 0x7f0b0075
			public const int edit_my_email = 2131427445;
			
			// aapt resource value: 0x7f0b0022
			public const int edit_newpass = 2131427362;
			
			// aapt resource value: 0x7f0b0021
			public const int edit_oldpass = 2131427361;
			
			// aapt resource value: 0x7f0b00bd
			public const int edit_pass_login = 2131427517;
			
			// aapt resource value: 0x7f0b00aa
			public const int edit_username_login = 2131427498;
			
			// aapt resource value: 0x7f0b00f3
			public const int frameLayout1 = 2131427571;
			
			// aapt resource value: 0x7f0b00e8
			public const int framlayout = 2131427560;
			
			// aapt resource value: 0x7f0b00b6
			public const int ic_license_status = 2131427510;
			
			// aapt resource value: 0x7f0b00cb
			public const int ic_license_status_detail = 2131427531;
			
			// aapt resource value: 0x7f0b0011
			public const int imageView1 = 2131427345;
			
			// aapt resource value: 0x7f0b00c8
			public const int imgChecked = 2131427528;
			
			// aapt resource value: 0x7f0b0037
			public const int imgEmailFollowUp = 2131427383;
			
			// aapt resource value: 0x7f0b0035
			public const int imgFavoriteFolowUp = 2131427381;
			
			// aapt resource value: 0x7f0b00e3
			public const int imgIconCallingStep2 = 2131427555;
			
			// aapt resource value: 0x7f0b00ea
			public const int imgIconStatus = 2131427562;
			
			// aapt resource value: 0x7f0b0033
			public const int imgRatingFolowUp = 2131427379;
			
			// aapt resource value: 0x7f0b0079
			public const int imgRatingReivew = 2131427449;
			
			// aapt resource value: 0x7f0b003f
			public const int imgReplayFollowUp = 2131427391;
			
			// aapt resource value: 0x7f0b0083
			public const int imgStar1 = 2131427459;
			
			// aapt resource value: 0x7f0b0084
			public const int imgStar2 = 2131427460;
			
			// aapt resource value: 0x7f0b0085
			public const int imgStar3 = 2131427461;
			
			// aapt resource value: 0x7f0b0086
			public const int imgStar4 = 2131427462;
			
			// aapt resource value: 0x7f0b00c6
			public const int imgStatus = 2131427526;
			
			// aapt resource value: 0x7f0b00e5
			public const int imgTab = 2131427557;
			
			// aapt resource value: 0x7f0b003b
			public const int imgTranscribeFollowUp = 2131427387;
			
			// aapt resource value: 0x7f0b00f9
			public const int imgURL = 2131427577;
			
			// aapt resource value: 0x7f0b003d
			public const int imgUpPhotoFollowUp = 2131427389;
			
			// aapt resource value: 0x7f0b0039
			public const int imgWaiveFeeFollowUp = 2131427385;
			
			// aapt resource value: 0x7f0b00d0
			public const int img_add_favorite_detail = 2131427536;
			
			// aapt resource value: 0x7f0b0051
			public const int img_add_favorite_pass = 2131427409;
			
			// aapt resource value: 0x7f0b0029
			public const int img_avatar_customer_calling = 2131427369;
			
			// aapt resource value: 0x7f0b00c9
			public const int img_avatar_spec_detail = 2131427529;
			
			// aapt resource value: 0x7f0b00d1
			public const int img_email_profile_detail = 2131427537;
			
			// aapt resource value: 0x7f0b0052
			public const int img_email_profile_pass = 2131427410;
			
			// aapt resource value: 0x7f0b00b5
			public const int img_ic_rating = 2131427509;
			
			// aapt resource value: 0x7f0b00ca
			public const int img_ic_rating_detail = 2131427530;
			
			// aapt resource value: 0x7f0b004f
			public const int img_num_rating_pass = 2131427407;
			
			// aapt resource value: 0x7f0b0053
			public const int img_rating_pass = 2131427411;
			
			// aapt resource value: 0x7f0b0030
			public const int img_upfile_calling = 2131427376;
			
			// aapt resource value: 0x7f0b0009
			public const int linearLayout1 = 2131427337;
			
			// aapt resource value: 0x7f0b0099
			public const int linearLayout2 = 2131427481;
			
			// aapt resource value: 0x7f0b0090
			public const int linearLayout4 = 2131427472;
			
			// aapt resource value: 0x7f0b004d
			public const int linearLayout5 = 2131427405;
			
			// aapt resource value: 0x7f0b0014
			public const int llActionBooking = 2131427348;
			
			// aapt resource value: 0x7f0b00f1
			public const int llBgStatus = 2131427569;
			
			// aapt resource value: 0x7f0b0016
			public const int llBookTime = 2131427350;
			
			// aapt resource value: 0x7f0b001c
			public const int llBookTime1 = 2131427356;
			
			// aapt resource value: 0x7f0b00f4
			public const int llButtonSegmented = 2131427572;
			
			// aapt resource value: 0x7f0b001d
			public const int llCallBack = 2131427357;
			
			// aapt resource value: 0x7f0b0054
			public const int llContentPass = 2131427412;
			
			// aapt resource value: 0x7f0b00ec
			public const int llDashBoard = 2131427564;
			
			// aapt resource value: 0x7f0b0036
			public const int llEmailFollowUp = 2131427382;
			
			// aapt resource value: 0x7f0b000f
			public const int llEndTimeBooking = 2131427343;
			
			// aapt resource value: 0x7f0b009a
			public const int llEndTimeReschedule = 2131427482;
			
			// aapt resource value: 0x7f0b0034
			public const int llFavoriteFollowUp = 2131427380;
			
			// aapt resource value: 0x7f0b005e
			public const int llFileAtachment = 2131427422;
			
			// aapt resource value: 0x7f0b0069
			public const int llFileAttachConfirmed = 2131427433;
			
			// aapt resource value: 0x7f0b00a6
			public const int llGrButtonConfirmReschedule = 2131427494;
			
			// aapt resource value: 0x7f0b00a2
			public const int llGrButtonDetailReschedule = 2131427490;
			
			// aapt resource value: 0x7f0b0031
			public const int llGrFollowUpAction = 2131427377;
			
			// aapt resource value: 0x7f0b0096
			public const int llGrSelectTimeReschedule = 2131427478;
			
			// aapt resource value: 0x7f0b0027
			public const int llGroupActionBar = 2131427367;
			
			// aapt resource value: 0x7f0b002b
			public const int llGroupCalling = 2131427371;
			
			// aapt resource value: 0x7f0b0066
			public const int llGroupEnquiry = 2131427430;
			
			// aapt resource value: 0x7f0b005a
			public const int llGroupFeePass = 2131427418;
			
			// aapt resource value: 0x7f0b0068
			public const int llGroupFileAttachBooking = 2131427432;
			
			// aapt resource value: 0x7f0b00df
			public const int llGroupStatus = 2131427551;
			
			// aapt resource value: 0x7f0b0041
			public const int llHeader = 2131427393;
			
			// aapt resource value: 0x7f0b0049
			public const int llProgressBar = 2131427401;
			
			// aapt resource value: 0x7f0b0032
			public const int llRatingFollowUp = 2131427378;
			
			// aapt resource value: 0x7f0b003e
			public const int llReplayFollowUp = 2131427390;
			
			// aapt resource value: 0x7f0b001f
			public const int llSchedule = 2131427359;
			
			// aapt resource value: 0x7f0b000d
			public const int llStartTimeBooking = 2131427341;
			
			// aapt resource value: 0x7f0b0097
			public const int llStartTimeReschedule = 2131427479;
			
			// aapt resource value: 0x7f0b00e9
			public const int llStatus = 2131427561;
			
			// aapt resource value: 0x7f0b0017
			public const int llTalkNowDetail = 2131427351;
			
			// aapt resource value: 0x7f0b003a
			public const int llTranscribeFollowUp = 2131427386;
			
			// aapt resource value: 0x7f0b003c
			public const int llUploadPhotoFollowUp = 2131427388;
			
			// aapt resource value: 0x7f0b0038
			public const int llWaiveFeeFollowUp = 2131427384;
			
			// aapt resource value: 0x7f0b0044
			public const int ll_Search = 2131427396;
			
			// aapt resource value: 0x7f0b002f
			public const int ll_file_attach_customer_calling = 2131427375;
			
			// aapt resource value: 0x7f0b0089
			public const int ll_grBtn_feedback = 2131427465;
			
			// aapt resource value: 0x7f0b00d3
			public const int ll_spec_detail = 2131427539;
			
			// aapt resource value: 0x7f0b0082
			public const int lv_priority_sort = 2131427458;
			
			// aapt resource value: 0x7f0b00fd
			public const int mainMenu = 2131427581;
			
			// aapt resource value: 0x7f0b0102
			public const int mainMenuPast = 2131427586;
			
			// aapt resource value: 0x7f0b00ff
			public const int overflow = 2131427583;
			
			// aapt resource value: 0x7f0b0103
			public const int overflowPast = 2131427587;
			
			// aapt resource value: 0x7f0b0040
			public const int progressBar1 = 2131427392;
			
			// aapt resource value: 0x7f0b00fc
			public const int refresh = 2131427580;
			
			// aapt resource value: 0x7f0b00fe
			public const int search = 2131427582;
			
			// aapt resource value: 0x7f0b00ad
			public const int searchView = 2131427501;
			
			// aapt resource value: 0x7f0b00b1
			public const int search_list_result = 2131427505;
			
			// aapt resource value: 0x7f0b0109
			public const int sort = 2131427593;
			
			// aapt resource value: 0x7f0b0101
			public const int sort_dashboard = 2131427585;
			
			// aapt resource value: 0x7f0b0081
			public const int sort_title = 2131427457;
			
			// aapt resource value: 0x7f0b0043
			public const int tabhost = 2131427395;
			
			// aapt resource value: 0x7f0b0106
			public const int talkReplay = 2131427590;
			
			// aapt resource value: 0x7f0b00c2
			public const int textView1 = 2131427522;
			
			// aapt resource value: 0x7f0b00c4
			public const int textView2 = 2131427524;
			
			// aapt resource value: 0x7f0b0072
			public const int timepicker_popup = 2131427442;
			
			// aapt resource value: 0x7f0b0107
			public const int transcript = 2131427591;
			
			// aapt resource value: 0x7f0b00d9
			public const int tvDayStandards = 2131427545;
			
			// aapt resource value: 0x7f0b00e4
			public const int tvDialStep2 = 2131427556;
			
			// aapt resource value: 0x7f0b001a
			public const int tvDolar = 2131427354;
			
			// aapt resource value: 0x7f0b0019
			public const int tvDolarStandard = 2131427353;
			
			// aapt resource value: 0x7f0b001b
			public const int tvDolarTalkNow = 2131427355;
			
			// aapt resource value: 0x7f0b00db
			public const int tvEndTimeStandard = 2131427547;
			
			// aapt resource value: 0x7f0b0006
			public const int tvErrorActiveCode = 2131427334;
			
			// aapt resource value: 0x7f0b0024
			public const int tvErrorChangePass = 2131427364;
			
			// aapt resource value: 0x7f0b00ab
			public const int tvErrorEmailResetPass = 2131427499;
			
			// aapt resource value: 0x7f0b00eb
			public const int tvExpertStatus = 2131427563;
			
			// aapt resource value: 0x7f0b007a
			public const int tvFeedbackReview = 2131427450;
			
			// aapt resource value: 0x7f0b00e6
			public const int tvNumberItemsTab = 2131427558;
			
			// aapt resource value: 0x7f0b00c7
			public const int tvSortContent = 2131427527;
			
			// aapt resource value: 0x7f0b00b4
			public const int tvSpecializationSearch = 2131427508;
			
			// aapt resource value: 0x7f0b0018
			public const int tvStar = 2131427352;
			
			// aapt resource value: 0x7f0b001e
			public const int tvStar3 = 2131427358;
			
			// aapt resource value: 0x7f0b0020
			public const int tvStar6 = 2131427360;
			
			// aapt resource value: 0x7f0b00d2
			public const int tvStar8 = 2131427538;
			
			// aapt resource value: 0x7f0b00da
			public const int tvStartTimeStandard = 2131427546;
			
			// aapt resource value: 0x7f0b00e7
			public const int tvTabTitle = 2131427559;
			
			// aapt resource value: 0x7f0b0028
			public const int tvTitleActionBar = 2131427368;
			
			// aapt resource value: 0x7f0b0042
			public const int tvTitleHeader = 2131427394;
			
			// aapt resource value: 0x7f0b0010
			public const int tv_book_time_end = 2131427344;
			
			// aapt resource value: 0x7f0b000e
			public const int tv_book_time_start = 2131427342;
			
			// aapt resource value: 0x7f0b0008
			public const int tv_book_time_title = 2131427336;
			
			// aapt resource value: 0x7f0b002d
			public const int tv_cost_customer_calling = 2131427373;
			
			// aapt resource value: 0x7f0b00f0
			public const int tv_created_date = 2131427568;
			
			// aapt resource value: 0x7f0b000a
			public const int tv_day_standardhours_select = 2131427338;
			
			// aapt resource value: 0x7f0b00bc
			public const int tv_detail_specialist = 2131427516;
			
			// aapt resource value: 0x7f0b00bb
			public const int tv_dolar = 2131427515;
			
			// aapt resource value: 0x7f0b0057
			public const int tv_end_date_past = 2131427415;
			
			// aapt resource value: 0x7f0b009b
			public const int tv_end_reschedule = 2131427483;
			
			// aapt resource value: 0x7f0b000c
			public const int tv_end_standardhours_select = 2131427340;
			
			// aapt resource value: 0x7f0b0058
			public const int tv_end_time_past = 2131427416;
			
			// aapt resource value: 0x7f0b0067
			public const int tv_enquiry_booking = 2131427431;
			
			// aapt resource value: 0x7f0b0005
			public const int tv_enquiry_error = 2131427333;
			
			// aapt resource value: 0x7f0b00a1
			public const int tv_enquiry_request_booking = 2131427489;
			
			// aapt resource value: 0x7f0b0088
			public const int tv_error_feedback = 2131427464;
			
			// aapt resource value: 0x7f0b00c0
			public const int tv_error_login = 2131427520;
			
			// aapt resource value: 0x7f0b0015
			public const int tv_expired_notice = 2131427349;
			
			// aapt resource value: 0x7f0b0095
			public const int tv_expried_time_reschedule = 2131427477;
			
			// aapt resource value: 0x7f0b0065
			public const int tv_fee_popup_booking = 2131427429;
			
			// aapt resource value: 0x7f0b009f
			public const int tv_fee_request_booking = 2131427487;
			
			// aapt resource value: 0x7f0b00c5
			public const int tv_forgotpass = 2131427525;
			
			// aapt resource value: 0x7f0b0026
			public const int tv_forgotpass_change = 2131427366;
			
			// aapt resource value: 0x7f0b00d7
			public const int tv_gst_spec_detail = 2131427543;
			
			// aapt resource value: 0x7f0b006e
			public const int tv_info_popup = 2131427438;
			
			// aapt resource value: 0x7f0b007d
			public const int tv_info_popup_notice = 2131427453;
			
			// aapt resource value: 0x7f0b00b9
			public const int tv_km = 2131427513;
			
			// aapt resource value: 0x7f0b00cd
			public const int tv_km_spec_detail = 2131427533;
			
			// aapt resource value: 0x7f0b00de
			public const int tv_language_spoken_spec_detail = 2131427550;
			
			// aapt resource value: 0x7f0b00b7
			public const int tv_licence_status = 2131427511;
			
			// aapt resource value: 0x7f0b00cc
			public const int tv_licence_status_detail = 2131427532;
			
			// aapt resource value: 0x7f0b00dc
			public const int tv_long_description_spec_detail = 2131427548;
			
			// aapt resource value: 0x7f0b00d4
			public const int tv_min_charge_specialist_detail = 2131427540;
			
			// aapt resource value: 0x7f0b00ef
			public const int tv_name_booking = 2131427567;
			
			// aapt resource value: 0x7f0b0050
			public const int tv_name_past_detail = 2131427408;
			
			// aapt resource value: 0x7f0b0061
			public const int tv_name_popup_booking = 2131427425;
			
			// aapt resource value: 0x7f0b0092
			public const int tv_name_request_booking = 2131427474;
			
			// aapt resource value: 0x7f0b00b3
			public const int tv_name_search = 2131427507;
			
			// aapt resource value: 0x7f0b002a
			public const int tv_name_spec_calling = 2131427370;
			
			// aapt resource value: 0x7f0b00b0
			public const int tv_noresult_search = 2131427504;
			
			// aapt resource value: 0x7f0b00ae
			public const int tv_notice_limit_search = 2131427502;
			
			// aapt resource value: 0x7f0b002e
			public const int tv_notice_waived_calling = 2131427374;
			
			// aapt resource value: 0x7f0b005c
			public const int tv_notice_waived_pass = 2131427420;
			
			// aapt resource value: 0x7f0b00ba
			public const int tv_ontime = 2131427514;
			
			// aapt resource value: 0x7f0b00cf
			public const int tv_ontime_detail = 2131427535;
			
			// aapt resource value: 0x7f0b00d5
			public const int tv_profession_spec_detail = 2131427541;
			
			// aapt resource value: 0x7f0b00dd
			public const int tv_qualifications_spec_detail = 2131427549;
			
			// aapt resource value: 0x7f0b00ee
			public const int tv_reference_booking = 2131427566;
			
			// aapt resource value: 0x7f0b00c3
			public const int tv_registry = 2131427523;
			
			// aapt resource value: 0x7f0b00d8
			public const int tv_short_description_spec_detail = 2131427544;
			
			// aapt resource value: 0x7f0b00d6
			public const int tv_specialisation_detail = 2131427542;
			
			// aapt resource value: 0x7f0b0055
			public const int tv_start_date_past = 2131427413;
			
			// aapt resource value: 0x7f0b0098
			public const int tv_start_reschedule = 2131427480;
			
			// aapt resource value: 0x7f0b000b
			public const int tv_start_standardhours_select = 2131427339;
			
			// aapt resource value: 0x7f0b0056
			public const int tv_start_time_past = 2131427414;
			
			// aapt resource value: 0x7f0b00b8
			public const int tv_status = 2131427512;
			
			// aapt resource value: 0x7f0b00f2
			public const int tv_status_booking = 2131427570;
			
			// aapt resource value: 0x7f0b00ce
			public const int tv_status_spec_detail = 2131427534;
			
			// aapt resource value: 0x7f0b00e1
			public const int tv_sub_waiting_call_1 = 2131427553;
			
			// aapt resource value: 0x7f0b00ed
			public const int tv_time_booking = 2131427565;
			
			// aapt resource value: 0x7f0b0012
			public const int tv_time_booking_error = 2131427346;
			
			// aapt resource value: 0x7f0b002c
			public const int tv_time_customer_calling = 2131427372;
			
			// aapt resource value: 0x7f0b009c
			public const int tv_time_error_reschedule = 2131427484;
			
			// aapt resource value: 0x7f0b0063
			public const int tv_time_popup_booking = 2131427427;
			
			// aapt resource value: 0x7f0b0094
			public const int tv_time_request_booking = 2131427476;
			
			// aapt resource value: 0x7f0b006d
			public const int tv_title_confirm_popup = 2131427437;
			
			// aapt resource value: 0x7f0b0064
			public const int tv_title_cost_confirm = 2131427428;
			
			// aapt resource value: 0x7f0b009d
			public const int tv_title_cost_reschedule = 2131427485;
			
			// aapt resource value: 0x7f0b007c
			public const int tv_title_notice_popup = 2131427452;
			
			// aapt resource value: 0x7f0b0062
			public const int tv_title_proposed_time = 2131427426;
			
			// aapt resource value: 0x7f0b008c
			public const int tv_title_request_popup = 2131427468;
			
			// aapt resource value: 0x7f0b005d
			public const int tv_total_cost_past = 2131427421;
			
			// aapt resource value: 0x7f0b005b
			public const int tv_total_fee_past = 2131427419;
			
			// aapt resource value: 0x7f0b0059
			public const int tv_total_time_past = 2131427417;
			
			// aapt resource value: 0x7f0b00e0
			public const int tv_waiting_call_1 = 2131427552;
			
			// aapt resource value: 0x7f0b00e2
			public const int tv_waiting_call_2 = 2131427554;
			
			// aapt resource value: 0x7f0b0105
			public const int uploadFile = 2131427589;
			
			// aapt resource value: 0x7f0b00f8
			public const int user_dashboard_list_result = 2131427576;
			
			// aapt resource value: 0x7f0b005f
			public const int videoView = 2131427423;
			
			// aapt resource value: 0x7f0b0093
			public const int view1 = 2131427475;
			
			// aapt resource value: 0x7f0b009e
			public const int view6 = 2131427486;
			
			// aapt resource value: 0x7f0b00a0
			public const int view7 = 2131427488;
			
			// aapt resource value: 0x7f0b0104
			public const int viewInvoice = 2131427588;
			
			// aapt resource value: 0x7f0b00af
			public const int viewSearch = 2131427503;
			
			// aapt resource value: 0x7f0b00f7
			public const int viewSegmented = 2131427575;
			
			// aapt resource value: 0x7f0b0108
			public const int waiveFee = 2131427592;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int active_code_layout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int book_a_time_schedule = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int booking_actions_layout = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int change_password = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int custom_action_bar_layout = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int customer_calling_layout = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int footer_loading_more = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int header_layout = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int home_dashboard = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int home_layout = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int indicator_progressbar_layout = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int my_profile = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int pastbooking_detail = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int play_audio_layout = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int popup_confirm_bookings = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int popup_confirm_layout = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int popup_date_time_picker = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int popup_enter_email = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int popup_feedback_review = 2130903058;
			
			// aapt resource value: 0x7f030013
			public const int popup_notice_layout = 2130903059;
			
			// aapt resource value: 0x7f030014
			public const int popup_option_select_photo = 2130903060;
			
			// aapt resource value: 0x7f030015
			public const int popup_priority_sort = 2130903061;
			
			// aapt resource value: 0x7f030016
			public const int popup_rating_feedback = 2130903062;
			
			// aapt resource value: 0x7f030017
			public const int popup_request_layout = 2130903063;
			
			// aapt resource value: 0x7f030018
			public const int popup_reschedule_booking = 2130903064;
			
			// aapt resource value: 0x7f030019
			public const int registry_webview_layout = 2130903065;
			
			// aapt resource value: 0x7f03001a
			public const int reset_password_layout = 2130903066;
			
			// aapt resource value: 0x7f03001b
			public const int search_layout = 2130903067;
			
			// aapt resource value: 0x7f03001c
			public const int search_list_adapter = 2130903068;
			
			// aapt resource value: 0x7f03001d
			public const int sign_in_layout = 2130903069;
			
			// aapt resource value: 0x7f03001e
			public const int sort_adapter_layout = 2130903070;
			
			// aapt resource value: 0x7f03001f
			public const int specialist_profile_layout = 2130903071;
			
			// aapt resource value: 0x7f030020
			public const int step_waiting_call = 2130903072;
			
			// aapt resource value: 0x7f030021
			public const int tab_dashboard = 2130903073;
			
			// aapt resource value: 0x7f030022
			public const int user_dashboard_layout = 2130903074;
			
			// aapt resource value: 0x7f030023
			public const int user_dashboard_list_adapter = 2130903075;
			
			// aapt resource value: 0x7f030024
			public const int user_dashboard_list_result = 2130903076;
			
			// aapt resource value: 0x7f030025
			public const int view_list_image_url_layout = 2130903077;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f0a0000
			public const int contextmenu = 2131361792;
			
			// aapt resource value: 0x7f0a0001
			public const int menu_dashboard = 2131361793;
			
			// aapt resource value: 0x7f0a0002
			public const int menu_past_history = 2131361794;
			
			// aapt resource value: 0x7f0a0003
			public const int menu_search_result = 2131361795;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f05003c
			public const int Decline = 2131034172;
			
			// aapt resource value: 0x7f050032
			public const int GST_apply = 2131034162;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			// aapt resource value: 0x7f0500b8
			public const int Specialisation_title = 2131034296;
			
			// aapt resource value: 0x7f0500cc
			public const int about_me_title = 2131034316;
			
			// aapt resource value: 0x7f0500a2
			public const int acc_locked = 2131034274;
			
			// aapt resource value: 0x7f0500e3
			public const int accept_defer_title = 2131034339;
			
			// aapt resource value: 0x7f0500fa
			public const int active_account_failed = 2131034362;
			
			// aapt resource value: 0x7f0500fb
			public const int active_account_successful = 2131034363;
			
			// aapt resource value: 0x7f0500f9
			public const int active_account_title = 2131034361;
			
			// aapt resource value: 0x7f050029
			public const int activity_message = 2131034153;
			
			// aapt resource value: 0x7f050028
			public const int activity_title = 2131034152;
			
			// aapt resource value: 0x7f05006e
			public const int add_file_btn = 2131034222;
			
			// aapt resource value: 0x7f050033
			public const int add_more_specialist = 2131034163;
			
			// aapt resource value: 0x7f050014
			public const int address = 2131034132;
			
			// aapt resource value: 0x7f050066
			public const int alerts_title = 2131034214;
			
			// aapt resource value: 0x7f05006a
			public const int alerts_title_popup = 2131034218;
			
			// aapt resource value: 0x7f050021
			public const int amount = 2131034145;
			
			// aapt resource value: 0x7f050002
			public const int app_name = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int app_title = 2131034115;
			
			// aapt resource value: 0x7f0500c6
			public const int applicable_cost_title = 2131034310;
			
			// aapt resource value: 0x7f050050
			public const int asap_confirm = 2131034192;
			
			// aapt resource value: 0x7f05004f
			public const int asap_confirm_title = 2131034191;
			
			// aapt resource value: 0x7f050051
			public const int asap_notice_end = 2131034193;
			
			// aapt resource value: 0x7f050052
			public const int asap_notice_end_title = 2131034194;
			
			// aapt resource value: 0x7f050074
			public const int asap_title = 2131034228;
			
			// aapt resource value: 0x7f05011c
			public const int availability_title = 2131034396;
			
			// aapt resource value: 0x7f0500e6
			public const int available_title = 2131034342;
			
			// aapt resource value: 0x7f050009
			public const int back = 2131034121;
			
			// aapt resource value: 0x7f05011f
			public const int beta_notice = 2131034399;
			
			// aapt resource value: 0x7f05007e
			public const int book_out_of_btn = 2131034238;
			
			// aapt resource value: 0x7f05007d
			public const int book_standard_btn = 2131034237;
			
			// aapt resource value: 0x7f050093
			public const int book_time = 2131034259;
			
			// aapt resource value: 0x7f05003f
			public const int book_time_request = 2131034175;
			
			// aapt resource value: 0x7f05003e
			public const int book_time_tile = 2131034174;
			
			// aapt resource value: 0x7f050067
			public const int booking_requests_title = 2131034215;
			
			// aapt resource value: 0x7f05006b
			public const int booking_requests_title_popup = 2131034219;
			
			// aapt resource value: 0x7f050039
			public const int brief_description = 2131034169;
			
			// aapt resource value: 0x7f050087
			public const int calling_title = 2131034247;
			
			// aapt resource value: 0x7f05003b
			public const int cancel = 2131034171;
			
			// aapt resource value: 0x7f05003d
			public const int cancel_consultation = 2131034173;
			
			// aapt resource value: 0x7f0500e4
			public const int cancel_defer_title = 2131034340;
			
			// aapt resource value: 0x7f0500f8
			public const int cannot_get_data = 2131034360;
			
			// aapt resource value: 0x7f05001e
			public const int card_number = 2131034142;
			
			// aapt resource value: 0x7f0500ec
			public const int change_pass_success_notice = 2131034348;
			
			// aapt resource value: 0x7f0500db
			public const int change_pass_title = 2131034331;
			
			// aapt resource value: 0x7f05004a
			public const int choosed_booking_title = 2131034186;
			
			// aapt resource value: 0x7f050046
			public const int comment_email_hint = 2131034182;
			
			// aapt resource value: 0x7f05002c
			public const int complete_title = 2131034156;
			
			// aapt resource value: 0x7f05003a
			public const int confirm = 2131034170;
			
			// aapt resource value: 0x7f0500a7
			public const int confirmPassRequired = 2131034279;
			
			// aapt resource value: 0x7f0500d3
			public const int confirm_button_title = 2131034323;
			
			// aapt resource value: 0x7f050073
			public const int confirm_decline_fee_info = 2131034227;
			
			// aapt resource value: 0x7f050071
			public const int confirm_decline_info = 2131034225;
			
			// aapt resource value: 0x7f050072
			public const int confirm_decline_no_fee_expert = 2131034226;
			
			// aapt resource value: 0x7f050070
			public const int confirm_info_title = 2131034224;
			
			// aapt resource value: 0x7f0500da
			public const int confirm_pass_title = 2131034330;
			
			// aapt resource value: 0x7f050068
			public const int confirmed_booking_title = 2131034216;
			
			// aapt resource value: 0x7f05006c
			public const int confirmed_booking_title_popup = 2131034220;
			
			// aapt resource value: 0x7f05006f
			public const int confirmed_time_title = 2131034223;
			
			// aapt resource value: 0x7f050025
			public const int congratulation = 2131034149;
			
			// aapt resource value: 0x7f05007f
			public const int connection_fail = 2131034239;
			
			// aapt resource value: 0x7f0500f2
			public const int connection_fee_info = 2131034354;
			
			// aapt resource value: 0x7f05005e
			public const int consultation_titile = 2131034206;
			
			// aapt resource value: 0x7f0500c5
			public const int consulting_fee_title = 2131034309;
			
			// aapt resource value: 0x7f050031
			public const int country_permitted = 2131034161;
			
			// aapt resource value: 0x7f05010d
			public const int customer_waived_fee_notice = 2131034381;
			
			// aapt resource value: 0x7f0500d1
			public const int dash_board_title = 2131034321;
			
			// aapt resource value: 0x7f0500d4
			public const int decline_button_title = 2131034324;
			
			// aapt resource value: 0x7f0500e0
			public const int delay_day_info = 2131034336;
			
			// aapt resource value: 0x7f0500e1
			public const int delay_day_info1 = 2131034337;
			
			// aapt resource value: 0x7f0500df
			public const int delay_minute_info = 2131034335;
			
			// aapt resource value: 0x7f0500e2
			public const int delay_tv_info = 2131034338;
			
			// aapt resource value: 0x7f0500de
			public const int delayed_title = 2131034334;
			
			// aapt resource value: 0x7f05011a
			public const int delete_fail = 2131034394;
			
			// aapt resource value: 0x7f050119
			public const int delete_title = 2131034393;
			
			// aapt resource value: 0x7f0500b5
			public const int detail_biography_title = 2131034293;
			
			// aapt resource value: 0x7f050091
			public const int deviceListening = 2131034257;
			
			// aapt resource value: 0x7f050089
			public const int dial = 2131034249;
			
			// aapt resource value: 0x7f05008e
			public const int disconnectSound = 2131034254;
			
			// aapt resource value: 0x7f0500b9
			public const int dolar_upto = 2131034297;
			
			// aapt resource value: 0x7f05002b
			public const int done = 2131034155;
			
			// aapt resource value: 0x7f0500c2
			public const int duration_title = 2131034306;
			
			// aapt resource value: 0x7f05000d
			public const int email = 2131034125;
			
			// aapt resource value: 0x7f05000e
			public const int email_confrim = 2131034126;
			
			// aapt resource value: 0x7f050038
			public const int email_profile = 2131034168;
			
			// aapt resource value: 0x7f050047
			public const int email_sender_require = 2131034183;
			
			// aapt resource value: 0x7f050063
			public const int end_title = 2131034211;
			
			// aapt resource value: 0x7f050043
			public const int enter_email = 2131034179;
			
			// aapt resource value: 0x7f050044
			public const int enter_email_instruction = 2131034180;
			
			// aapt resource value: 0x7f050048
			public const int error_login = 2131034184;
			
			// aapt resource value: 0x7f050118
			public const int expert_dial_title = 2131034392;
			
			// aapt resource value: 0x7f05010e
			public const int expert_waived_fee_notice = 2131034382;
			
			// aapt resource value: 0x7f05001f
			public const int expiration_date = 2131034143;
			
			// aapt resource value: 0x7f05010a
			public const int expired_content = 2131034378;
			
			// aapt resource value: 0x7f05011d
			public const int expired_notice = 2131034397;
			
			// aapt resource value: 0x7f0500fc
			public const int expired_session = 2131034364;
			
			// aapt resource value: 0x7f050107
			public const int expired_time_notice = 2131034375;
			
			// aapt resource value: 0x7f050114
			public const int expired_time_request_talkNow_notice = 2131034388;
			
			// aapt resource value: 0x7f050109
			public const int expired_title = 2131034377;
			
			// aapt resource value: 0x7f050007
			public const int favorite_title = 2131034119;
			
			// aapt resource value: 0x7f0500d6
			public const int favorites_title = 2131034326;
			
			// aapt resource value: 0x7f050036
			public const int favourite = 2131034166;
			
			// aapt resource value: 0x7f050078
			public const int feeback_error = 2131034232;
			
			// aapt resource value: 0x7f0500f5
			public const int feedback_hind = 2131034357;
			
			// aapt resource value: 0x7f0500f4
			public const int feedback_title = 2131034356;
			
			// aapt resource value: 0x7f05011b
			public const int file_not_exist = 2131034395;
			
			// aapt resource value: 0x7f050012
			public const int first_name = 2131034130;
			
			// aapt resource value: 0x7f05002d
			public const int forgot_pass = 2131034157;
			
			// aapt resource value: 0x7f050019
			public const int geepers = 2131034137;
			
			// aapt resource value: 0x7f05001a
			public const int geepers_name = 2131034138;
			
			// aapt resource value: 0x7f050102
			public const int get_img_from_lib = 2131034370;
			
			// aapt resource value: 0x7f0500bf
			public const int gps_cancel = 2131034303;
			
			// aapt resource value: 0x7f0500be
			public const int gps_enable = 2131034302;
			
			// aapt resource value: 0x7f0500bd
			public const int gps_request = 2131034301;
			
			// aapt resource value: 0x7f0500b2
			public const int gst_applied_title = 2131034290;
			
			// aapt resource value: 0x7f0500bb
			public const int gst_title = 2131034299;
			
			// aapt resource value: 0x7f05008a
			public const int hangup = 2131034250;
			
			// aapt resource value: 0x7f05000f
			public const int homephone = 2131034127;
			
			// aapt resource value: 0x7f05008f
			public const int iWantThisToSayStuff = 2131034255;
			
			// aapt resource value: 0x7f05008d
			public const int incomingSound = 2131034253;
			
			// aapt resource value: 0x7f050040
			public const int info1 = 2131034176;
			
			// aapt resource value: 0x7f050041
			public const int info2 = 2131034177;
			
			// aapt resource value: 0x7f050042
			public const int info3 = 2131034178;
			
			// aapt resource value: 0x7f050027
			public const int info_acti = 2131034151;
			
			// aapt resource value: 0x7f0500e9
			public const int invalid_email_reset = 2131034345;
			
			// aapt resource value: 0x7f050077
			public const int invalid_email_title = 2131034231;
			
			// aapt resource value: 0x7f0500a1
			public const int invalid_pass = 2131034273;
			
			// aapt resource value: 0x7f05009f
			public const int invalid_user_pass = 2131034271;
			
			// aapt resource value: 0x7f0500b7
			public const int language_spoken_title = 2131034295;
			
			// aapt resource value: 0x7f050013
			public const int last_name = 2131034131;
			
			// aapt resource value: 0x7f050030
			public const int licence_title = 2131034160;
			
			// aapt resource value: 0x7f05011e
			public const int limit_search_result = 2131034398;
			
			// aapt resource value: 0x7f05005d
			public const int loading_content = 2131034205;
			
			// aapt resource value: 0x7f05005c
			public const int loading_title = 2131034204;
			
			// aapt resource value: 0x7f050024
			public const int master = 2131034148;
			
			// aapt resource value: 0x7f05009c
			public const int max_endTime_err = 2131034268;
			
			// aapt resource value: 0x7f05009a
			public const int max_startTime_err = 2131034266;
			
			// aapt resource value: 0x7f0500e7
			public const int maybe_available_title = 2131034343;
			
			// aapt resource value: 0x7f05009b
			public const int min_endTime_err = 2131034267;
			
			// aapt resource value: 0x7f050099
			public const int min_startTime_err = 2131034265;
			
			// aapt resource value: 0x7f0500f1
			public const int minimum_charge_info = 2131034353;
			
			// aapt resource value: 0x7f050010
			public const int mobilephone = 2131034128;
			
			// aapt resource value: 0x7f050092
			public const int muted = 2131034258;
			
			// aapt resource value: 0x7f050045
			public const int my_email_hint = 2131034181;
			
			// aapt resource value: 0x7f0500d5
			public const int my_profile_title = 2131034325;
			
			// aapt resource value: 0x7f05001d
			public const int name_on_card = 2131034141;
			
			// aapt resource value: 0x7f050011
			public const int name_upload = 2131034129;
			
			// aapt resource value: 0x7f050116
			public const int network_disconnect = 2131034390;
			
			// aapt resource value: 0x7f050117
			public const int network_not_available = 2131034391;
			
			// aapt resource value: 0x7f050115
			public const int network_title = 2131034389;
			
			// aapt resource value: 0x7f0500a6
			public const int newPassRequired = 2131034278;
			
			// aapt resource value: 0x7f0500d9
			public const int new_pass_title = 2131034329;
			
			// aapt resource value: 0x7f050008
			public const int next = 2131034120;
			
			// aapt resource value: 0x7f0500f3
			public const int no_favorite_title = 2131034355;
			
			// aapt resource value: 0x7f0500af
			public const int no_result_search = 2131034287;
			
			// aapt resource value: 0x7f0500e8
			public const int not_available_title = 2131034344;
			
			// aapt resource value: 0x7f0500ee
			public const int notice_inactive_account = 2131034350;
			
			// aapt resource value: 0x7f05007c
			public const int ok_btn = 2131034236;
			
			// aapt resource value: 0x7f0500a5
			public const int oldPassRequired = 2131034277;
			
			// aapt resource value: 0x7f0500d8
			public const int old_pass_title = 2131034328;
			
			// aapt resource value: 0x7f050108
			public const int on_time_status = 2131034376;
			
			// aapt resource value: 0x7f050090
			public const int options = 2131034256;
			
			// aapt resource value: 0x7f0500c4
			public const int order_transcript = 2131034308;
			
			// aapt resource value: 0x7f050096
			public const int out_of_time = 2131034262;
			
			// aapt resource value: 0x7f05009e
			public const int out_of_time_error = 2131034270;
			
			// aapt resource value: 0x7f05008c
			public const int outgoingSound = 2131034252;
			
			// aapt resource value: 0x7f05000b
			public const int pass = 2131034123;
			
			// aapt resource value: 0x7f0500a4
			public const int passRequired = 2131034276;
			
			// aapt resource value: 0x7f05000c
			public const int pass_confirm = 2131034124;
			
			// aapt resource value: 0x7f0500dd
			public const int pass_confirm_error_content = 2131034333;
			
			// aapt resource value: 0x7f0500dc
			public const int pass_required_content = 2131034332;
			
			// aapt resource value: 0x7f050069
			public const int past_booking_title = 2131034217;
			
			// aapt resource value: 0x7f05006d
			public const int past_booking_title_popup = 2131034221;
			
			// aapt resource value: 0x7f050022
			public const int payment_method = 2131034146;
			
			// aapt resource value: 0x7f050018
			public const int postcode = 2131034136;
			
			// aapt resource value: 0x7f050055
			public const int pre_time_confirm = 2131034197;
			
			// aapt resource value: 0x7f050054
			public const int pre_time_confirm_outof_title = 2131034196;
			
			// aapt resource value: 0x7f050053
			public const int pre_time_confirm_standard_title = 2131034195;
			
			// aapt resource value: 0x7f050056
			public const int pre_time_notice_end1 = 2131034198;
			
			// aapt resource value: 0x7f050057
			public const int pre_time_notice_end2 = 2131034199;
			
			// aapt resource value: 0x7f050058
			public const int pre_time_notice_end3 = 2131034200;
			
			// aapt resource value: 0x7f050059
			public const int pre_time_notice_end4 = 2131034201;
			
			// aapt resource value: 0x7f05005b
			public const int pre_time_notice_end_title = 2131034203;
			
			// aapt resource value: 0x7f050037
			public const int prefered_time = 2131034167;
			
			// aapt resource value: 0x7f050095
			public const int preferred_time = 2131034261;
			
			// aapt resource value: 0x7f05005f
			public const int price_per_minute = 2131034207;
			
			// aapt resource value: 0x7f0500b1
			public const int profession_title = 2131034289;
			
			// aapt resource value: 0x7f0500ba
			public const int proof_title = 2131034298;
			
			// aapt resource value: 0x7f0500b6
			public const int qualification_title = 2131034294;
			
			// aapt resource value: 0x7f0500c0
			public const int rate_advice_cus = 2131034304;
			
			// aapt resource value: 0x7f0500c1
			public const int rate_advice_spec = 2131034305;
			
			// aapt resource value: 0x7f05008b
			public const int ready = 2131034251;
			
			// aapt resource value: 0x7f0500cd
			public const int reference_title = 2131034317;
			
			// aapt resource value: 0x7f050005
			public const int regis_customer_title = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int regis_special_title = 2131034118;
			
			// aapt resource value: 0x7f05002f
			public const int register = 2131034159;
			
			// aapt resource value: 0x7f0500ed
			public const int registry_title = 2131034349;
			
			// aapt resource value: 0x7f05002e
			public const int remember = 2131034158;
			
			// aapt resource value: 0x7f050100
			public const int replay_not_exist_notice = 2131034368;
			
			// aapt resource value: 0x7f0500c3
			public const int replay_title = 2131034307;
			
			// aapt resource value: 0x7f050080
			public const int request_fail = 2131034240;
			
			// aapt resource value: 0x7f050081
			public const int request_success = 2131034241;
			
			// aapt resource value: 0x7f050101
			public const int require_email_profile = 2131034369;
			
			// aapt resource value: 0x7f0500fe
			public const int require_update_profile_content = 2131034366;
			
			// aapt resource value: 0x7f0500ff
			public const int require_update_profile_title = 2131034367;
			
			// aapt resource value: 0x7f050064
			public const int reschedule_btn = 2131034212;
			
			// aapt resource value: 0x7f0500d2
			public const int reschedule_button_title = 2131034322;
			
			// aapt resource value: 0x7f050065
			public const int reschedule_notice = 2131034213;
			
			// aapt resource value: 0x7f0500e5
			public const int reschedule_tv_info = 2131034341;
			
			// aapt resource value: 0x7f050083
			public const int reset_pass_content = 2131034243;
			
			// aapt resource value: 0x7f050084
			public const int reset_pass_hind_title = 2131034244;
			
			// aapt resource value: 0x7f0500ea
			public const int reset_pass_success = 2131034346;
			
			// aapt resource value: 0x7f050086
			public const int reset_pass_title = 2131034246;
			
			// aapt resource value: 0x7f050061
			public const int schedule_btn = 2131034209;
			
			// aapt resource value: 0x7f050049
			public const int search_hint = 2131034185;
			
			// aapt resource value: 0x7f0500cf
			public const int search_result_title = 2131034319;
			
			// aapt resource value: 0x7f0500d7
			public const int search_tab_title = 2131034327;
			
			// aapt resource value: 0x7f0500d0
			public const int search_title = 2131034320;
			
			// aapt resource value: 0x7f050020
			public const int security_code = 2131034144;
			
			// aapt resource value: 0x7f05001c
			public const int selectpayment = 2131034140;
			
			// aapt resource value: 0x7f050097
			public const int sendEmailTitle = 2131034263;
			
			// aapt resource value: 0x7f050082
			public const int send_email_success = 2131034242;
			
			// aapt resource value: 0x7f0500f6
			public const int send_feedback = 2131034358;
			
			// aapt resource value: 0x7f0500f7
			public const int send_feedback_success = 2131034359;
			
			// aapt resource value: 0x7f050085
			public const int send_reset_pass_title = 2131034245;
			
			// aapt resource value: 0x7f050076
			public const int sending_request_title = 2131034230;
			
			// aapt resource value: 0x7f0500a0
			public const int server_err = 2131034272;
			
			// aapt resource value: 0x7f0500b3
			public const int short_description_title = 2131034291;
			
			// aapt resource value: 0x7f05005a
			public const int show_password = 2131034202;
			
			// aapt resource value: 0x7f0500ce
			public const int sign_in_title = 2131034318;
			
			// aapt resource value: 0x7f050079
			public const int sign_out_title = 2131034233;
			
			// aapt resource value: 0x7f050004
			public const int signin_title = 2131034116;
			
			// aapt resource value: 0x7f0500eb
			public const int signout_confirm = 2131034347;
			
			// aapt resource value: 0x7f050094
			public const int soonest_available_time = 2131034260;
			
			// aapt resource value: 0x7f050060
			public const int soonest_possible_time = 2131034208;
			
			// aapt resource value: 0x7f0500bc
			public const int sort_by_title = 2131034300;
			
			// aapt resource value: 0x7f0500b4
			public const int standard_time = 2131034292;
			
			// aapt resource value: 0x7f05009d
			public const int standard_time_error = 2131034269;
			
			// aapt resource value: 0x7f050062
			public const int start_title = 2131034210;
			
			// aapt resource value: 0x7f0500a9
			public const int strAwaitingToCustomer = 2131034281;
			
			// aapt resource value: 0x7f0500a8
			public const int strAwaitingToSpec = 2131034280;
			
			// aapt resource value: 0x7f0500ab
			public const int strCusToSchedule = 2131034283;
			
			// aapt resource value: 0x7f0500aa
			public const int strSpecToSchedule = 2131034282;
			
			// aapt resource value: 0x7f0500ac
			public const int str_enquiry_empty = 2131034284;
			
			// aapt resource value: 0x7f0500ad
			public const int str_info_add_favorite = 2131034285;
			
			// aapt resource value: 0x7f0500ae
			public const int str_info_remove_favorite = 2131034286;
			
			// aapt resource value: 0x7f0500b0
			public const int str_notice_end = 2131034288;
			
			// aapt resource value: 0x7f050016
			public const int street = 2131034134;
			
			// aapt resource value: 0x7f050015
			public const int street_number = 2131034133;
			
			// aapt resource value: 0x7f05002a
			public const int submit = 2131034154;
			
			// aapt resource value: 0x7f050017
			public const int suburb = 2131034135;
			
			// aapt resource value: 0x7f050088
			public const int talkNow_title_button = 2131034248;
			
			// aapt resource value: 0x7f0500c9
			public const int talk_replay = 2131034313;
			
			// aapt resource value: 0x7f050035
			public const int talknow = 2131034165;
			
			// aapt resource value: 0x7f050110
			public const int talknow_cancel_notice = 2131034384;
			
			// aapt resource value: 0x7f05004e
			public const int talknow_confirm = 2131034190;
			
			// aapt resource value: 0x7f050111
			public const int talknow_notice_balance = 2131034385;
			
			// aapt resource value: 0x7f050112
			public const int talknow_notice_inprogress = 2131034386;
			
			// aapt resource value: 0x7f05010f
			public const int talknow_notice_title = 2131034383;
			
			// aapt resource value: 0x7f0500ca
			public const int terms_conditions = 2131034314;
			
			// aapt resource value: 0x7f0500cb
			public const int terms_title = 2131034315;
			
			// aapt resource value: 0x7f050026
			public const int thanks = 2131034150;
			
			// aapt resource value: 0x7f05010c
			public const int time_up_content = 2131034380;
			
			// aapt resource value: 0x7f05010b
			public const int time_up_title = 2131034379;
			
			// aapt resource value: 0x7f05001b
			public const int timezone = 2131034139;
			
			// aapt resource value: 0x7f05004d
			public const int titleTalknowConfirm = 2131034189;
			
			// aapt resource value: 0x7f050098
			public const int titleTalknowRequest = 2131034264;
			
			// aapt resource value: 0x7f05004c
			public const int title_notice = 2131034188;
			
			// aapt resource value: 0x7f05004b
			public const int title_select_time = 2131034187;
			
			// aapt resource value: 0x7f050075
			public const int today_title = 2131034229;
			
			// aapt resource value: 0x7f0500fd
			public const int transcribe_title = 2131034365;
			
			// aapt resource value: 0x7f050113
			public const int twilio_expired = 2131034387;
			
			// aapt resource value: 0x7f0500f0
			public const int upfile_title = 2131034352;
			
			// aapt resource value: 0x7f0500ef
			public const int uploadPhotoFail = 2131034351;
			
			// aapt resource value: 0x7f0500c8
			public const int upload_file_title = 2131034312;
			
			// aapt resource value: 0x7f050034
			public const int upload_photo = 2131034164;
			
			// aapt resource value: 0x7f0500a3
			public const int userNameRequired = 2131034275;
			
			// aapt resource value: 0x7f05000a
			public const int username = 2131034122;
			
			// aapt resource value: 0x7f0500c7
			public const int view_invoice_title = 2131034311;
			
			// aapt resource value: 0x7f050023
			public const int visa = 2131034147;
			
			// aapt resource value: 0x7f05007b
			public const int waiting = 2131034235;
			
			// aapt resource value: 0x7f050106
			public const int waive_fee_content = 2131034374;
			
			// aapt resource value: 0x7f050105
			public const int waive_fee_expired = 2131034373;
			
			// aapt resource value: 0x7f050104
			public const int waive_fee_expired_title = 2131034372;
			
			// aapt resource value: 0x7f050103
			public const int waive_fee_title = 2131034371;
			
			// aapt resource value: 0x7f05007a
			public const int welcome = 2131034234;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public const int ActionBarTheme = 2131165184;
			
			// aapt resource value: 0x7f070005
			public const int Mono_Android_Theme_Splash = 2131165189;
			
			// aapt resource value: 0x7f070001
			public const int MyActionBar = 2131165185;
			
			// aapt resource value: 0x7f070003
			public const int MyActionBarTabText = 2131165187;
			
			// aapt resource value: 0x7f070002
			public const int MyActionBarTitleText = 2131165186;
			
			// aapt resource value: 0x7f070004
			public const int Theme_Splash = 2131165188;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] RobotoTextView = new int[] {
					2130771968};
			
			// aapt resource value: 0
			public const int RobotoTextView_typeface = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
